### ISSUE TITLE
Refactor and prepare bar charts for public usage

### ISSUE THREAD

**Issue by vyoung831** [vyoung831/ChartView#16]
**Feature description**
This epic involves refactoring BarChart for reliability and easier servicability/collaboration.

**Acceptance criteria**
This issue can be closed when the following acceptance criteria are satisfied:
- [ ] Bar chart's areas of missing AUT are defined and issues are opened that cover that work.
- [ ] Bar chart's areas of missing manual testing are defined and issues are opened that cover that work.
- [ ] vyoung831/ChartView's README introduces BarChart and its intended usage.
- [ ] Notable parts of Bar Chart development are added to PR template checklist.
- [ ] Sufficient comments are written for BarChart code.
