### ISSUE TITLE
Refactor and prepare pie charts for public usage

### ISSUE THREAD

**Issue by vyoung831** [vyoung831/ChartView#17]
**Feature description**
This epic involves refactoring PieChart for reliability and easier servicability/collaboration.

**Acceptance criteria**
This issue can be closed when the following acceptance criteria are satisfied:
- [ ] Pie chart's areas of missing AUT are defined and issues are opened that cover that work.
- [ ] Pie chart's areas of missing manual testing are defined and issues are opened that cover that work.
- [ ] vyoung831/ChartView's README introduces PieChart and its intended usage.
- [ ] Notable parts of Pie Chart development are added to PR template checklist.
- [ ] Sufficient comments are written for PieChart code.
