### ISSUE TITLE
Refactor and prepare LineChartView for public usage

### ISSUE THREAD

**Issue by vyoung831** [vyoung831/ChartView#20]
**Feature description**
This epic involves refactoring LineChartView for reliability and easier servicability/collaboration.

**Acceptance criteria**
This issue can be closed when the following acceptance criteria are satisfied:
- [ ] LineChartView's areas of missing AUT are defined and issues are opened that cover that work.
- [ ] LineChartView's areas of missing manual testing are defined and issues are opened that cover that work.
- [ ] vyoung831/ChartView's README introduces LineChartView and its intended usage.
- [ ] Notable parts of LineChartView development are added to PR template checklist.
- [ ] Sufficient comments are written for LineChartView code.
