### ISSUE TITLE
Refactor and prepare MultiLineChartView for public usage

### ISSUE THREAD

**Issue by vyoung831** [vyoung831/ChartView#22]
**Feature description**
This epic involves refactoring MultiLineChartView for reliability and easier servicability/collaboration.

**Acceptance criteria**
This issue can be closed when the following acceptance criteria are satisfied:
- [ ] MultiLineChartView's areas of missing AUT are defined and issues are opened that cover that work.
- [ ] MultiLineChartView's areas of missing manual testing are defined and issues are opened that cover that work.
- [ ] vyoung831/ChartView's README introduces MultiLineChartView and its intended usage.
- [ ] Notable parts of MultiLineChartView development are added to PR template checklist.
- [ ] Sufficient comments are written for MultiLineChartView code.
